package io.simplesource.saga.action.async;

import io.simplesource.data.Result;

import java.util.function.Consumer;

/**
 * The Callback interface.
 *
 * @param <O> the output type generated by the
 */
@FunctionalInterface
public interface Callback<O> {
    /**
     * A function that is called during the async invocation to pass the return value back to the action processor.
     *
     * @param result the result - either a {@link Throwable} if there is an error, or the return value O
     */
    void complete(Result<Throwable, O> result);
}
